### ISSUE TITLE
Add trigger for today and tomorrows lowest prices

### ISSUE THREAD

**Issue by antonhagg** [tibber/com.tibber.athom#32] opened 2022-02-15 23:25 UTC
I really like The feature to trigger things when the price is low. But Even better would add Futures prices when they become available i.e. "Current price is one of today's and tomorrows lowest/highest [x] prices". The reson for this is that sometimes the car start to charge at 21:00 because the price is low within that day but usually the price drops after midnigt so it would have been better to start the charging after midnigt instead.

**Comment by lovethyresson** [comment] 2022-02-16 06:37
Hey,

Just thinking aloud here, but would you be able to combine, price is one of todays lowest hours with current price is at its lowest among the next x hours? Where x = 8 hours for example.

In all likelihood, charging will always happen at night anyway I assume.

**Comment by antonhagg** [comment] 2022-02-16 08:28
> Hey,
> 
> Just thinking aloud here, but would you be able to combine, price is one of todays lowest hours with current price is at its lowest among the next x hours? Where x = 8 hours for example.
> 
> In all likelihood, charging will always happen at night anyway I assume.

I didn't really understand. As far as I know there are only two triggers, one is "price is lowest of today" and The other is "price is lowest x of the day".

**Comment by lovethyresson** [comment] 2022-02-16 08:31
If you use price changed as a trigger, there are a lot more **and ** conditions you can use.

**Comment by antonhagg** [comment] 2022-02-16 08:41
> If you use price changed as a trigger, there are a lot more **and ** conditions you can use.

Now I think what you mean, its not really optimal, because this will only become true when the price is "the lowest" what if there is a  massive jump in price the hour after the price is the lowest?

**Comment by lovethyresson** [comment] 2022-02-16 18:23
I'd say the best thing here would be to have a price changed card that evaluates every hour if it shod charge. If true start charging, else stop charging.

Wouldn't that work?

**Comment by antonhagg** [comment] 2022-02-16 18:47
Thats what I have at The moment. If "price change" and "current price is one of todays 5 lowest" then "charge". How would you write it to also cobsider next days prices?

**Comment by lovethyresson** [comment] 2022-02-16 18:53
Would this work?![image](https://user-images.githubusercontent.com/57791059/154335606-20f63d9d-4a50-40a2-8a51-362d7e696d8e.png)![image](https://user-images.githubusercontent.com/57791059/154335630-d9266de9-1f00-409b-b7e8-907a61945371.png)

**Comment by lovethyresson** [comment] 2022-02-16 19:00
Basically, your concern is that you start charging at 23:00 when it would've been cheaper to wait until after midnight?

I see your point. I'll keep it in mind for the next iteration, meanwhile would something like this do it?

![image](https://user-images.githubusercontent.com/57791059/154336581-93672ed0-09b1-4386-a856-a2abe8e2b954.png)

**Comment by antonhagg** [comment] 2022-02-16 23:01
If I understand this condition correct the second contition wil make the charge wait untill 4 this morning and then start to charge but will soon stop because of the first condition.
![3F118F83-CA1A-41A1-BF90-CA9FD4E00681](https://user-images.githubusercontent.com/16721156/154371838-e9be124a-9089-4dff-8e06-8e33d2f2a95a.png)

**Comment by MagnusPer** [comment] 2022-11-02 12:49
I think my wish of a new card is the same where I want to pick the X lowest prices between two hours. Like the card to be like: Pick x cheapest hours between (tag) and (tag).

**Comment by jstaro** [comment] 2022-11-07 12:41
@MagnusPer 
In your example, could you not use `when` condition `at its lowest among the next X hours` plus an `and` condition for `time between 2:00 and 7:00`?

**Comment by MagnusPer** [comment] 2022-11-07 13:35
The problem is the card `Current price at its X lowest among the next Y hours` is not available in the Tibber app portfolio! The closest we come is 

![image](https://user-images.githubusercontent.com/35903236/200323274-fd1c4bd7-0b01-4c31-8385-256b0cca0295.png)

But it does not define how many hour slots i.e. the **X**

**Comment by jstaro** [comment] 2022-11-07 21:08
Ah, I see; we only have the "percentage" cards with two parameters. I misremembered. My bad! Looks like we have a feature gap here.

**Comment by MagnusPer** [comment] 2022-12-13 20:19
Tibber Friends.
Is there any progress or plan of implementing the wanted feature described in this issue?

**Comment by emilialu** [comment] 2022-12-15 11:53
Hello @MagnusPer!

  We have it in our roadmap, but can’t say for sure when we will be able to release it.  
  
  Also, the app is open sourced, so if someone wants to contribute the feature, we would be happy to review and test it! 😄

**Comment by emilialu** [comment] 2023-02-17 14:04
Hello,   

Version 1.8.8 is now available for test at https://homey.app/a/com.tibber/test/ 
With a new condition card: `Current price is one of the [x] lowest prices between [y] and [z] `
Please test it out and report any problems you find!

**Comment by MagnusPer** [comment] 2023-02-17 15:04
@emilialu - Super duper!  
I tried to download the test version from https://homey.app/sv-se/app/com.tibber/Tibber/test/ but a failure occurred stating

![image](https://user-images.githubusercontent.com/35903236/219690210-fcc85b88-db83-4cfd-a771-12c5b4bd386b.png)

**Comment by emilialu** [comment] 2023-02-18 08:59
And I have noticed during the night that the card still has a small bug that needs to be fixed. Will hopefully come back with a new build next week!

**Comment by MagnusPer** [comment] 2023-02-19 09:28
Maybe the same bug you found @emilialu, but I will anyway describe what I noticed.

I used below flow where Tibber_Price_2 works as expected but the Tibber_Price_1 doesn't report which I guess depends that the conditions runs over midnight? 

![image](https://user-images.githubusercontent.com/35903236/219938199-37519f5a-004a-4173-8852-1719fbb9864d.png)

Reporting 
![image](https://user-images.githubusercontent.com/35903236/219939852-57b1bad1-9679-43a0-b053-3cb0a56b4684.png)

Electrical price levels during the period  
![image](https://user-images.githubusercontent.com/35903236/219938328-5cb2fa1d-8625-4c30-ba6f-7db13e0eac35.png)

**Comment by emilialu** [comment] 2023-02-22 11:31
Yes exactly that. 
I released a new test build where these issues should be fixed. So please try it out!
https://homey.app/a/com.tibber/test/

**Comment by MagnusPer** [comment] 2023-02-24 07:40
Great job! I have tested the update during two nights and it works now as expected

**Comment by MagnusPer** [comment] 2023-02-24 07:59
@antonhagg - You opened this ticket, does this solution also fulfill your initial need?

**Comment by MagnusPer** [comment] 2023-02-27 07:22
@emilialu 
Some strange behavior this night (2023-02-27), I have requested for the 3 lowest hours but got 5 hours! I think this is due to the fact 2 hours had the same price 
23-00 > 1.00
**00-01 > 1.03**
**01-02 > 1.03**
02-03 > 1.01
03-04 > 1.12

![image](https://user-images.githubusercontent.com/35903236/221498501-875bfbc4-8410-44c0-b247-9b62811dc5cf.png)

**Comment by emilialu** [comment] 2023-02-28 10:16
Hello @MagnusPer,

That is indeed some odd behaviour. And you're sure you don't have additional flows or anything else that could have influenced your test graph?

I've had flows going with this new card with the same specs 22-06 and 3 lowest hours. And it has worked like intended since the latest test build. I checked with some others that also have used it and they haven't had any problems either. Which is why I want to check if there is any possibility that something else could have affected your test graph?

**Comment by MagnusPer** [comment] 2023-03-02 11:44
My bad! you have correct @emilialu that it was something else that triggered this. I have now used the new card during 2 nights and it works flawless.

**Closed** 2023-03-02 19:22 UTC
