### ISSUE TITLE
Tibber fails to fetch data in Homey

### ISSUE THREAD

**Issue by Coderaxx** [tibber/com.tibber.athom#27] opened 2021-12-27 01:01 UTC
Had issues with nothing updating in Homey, and tried removing Tibber and reinstalling it on Homey. This is what appears after reinstalling, when trying to add Home and Tibber Pulse.

Running Homey Bridge.
![0F5A36B5-7847-49FF-82C1-49C17A8DB5EA](https://user-images.githubusercontent.com/48462275/147424463-6ad40345-ebee-4f1e-8047-6e0f0638e7cf.png)

**Comment by jstaro** [comment] 2021-12-28 15:23
Could you please reproduce the error and then send an app diagnostic report? (More -> Apps -> Tibber -> [cog wheel] -> Create diagnostic report).

Also please add a note to the diagnostic report referring to this issue so we can easily correlate it.

**Comment by Coderaxx** [comment] 2021-12-28 17:15
Can’t find a way to create a diagnostics report when I’m using Homey bridge.

**Comment by johntrygve-haaverstad** [comment] 2021-12-28 21:24
I've got the same problem. 'Failed to retrieve data' message after tibber login when installing tibber app in homey.

**Comment by jstaro** [comment] 2021-12-29 13:56
> Can’t find a way to create a diagnostics report when I’m using Homey bridge.

Oh man, you're right. You can't do that unless you have a Homey Pro, looks like. That's... unfortunate.

What seems to be happening here (without having any diagnostics to go on) is that the request to fetch the your home(s) and related devices fails for some reason. Without knowing more, it could be a number of things.

Are you able to test to see if you can query your home using the [public Tibber API](https://developer.tibber.com/) (which Homey is using)? 
1. Sign in with your Tibber customer account (top right)
2. Press `Get an access token` and then `Create token`. Be sure to read the important notice there and not leak your token to third parties.
2. Go to API Explorer
3. Press `Load personal token`
4. You can now query the API in the same way the Tibber app for Homey does

There are some example queries in the dropdown to the right if you're not familiar with GraphQL syntax/playground.

**Comment by Coderaxx** [comment] 2021-12-30 00:43
Tried both in the API explorer, and on my own. Works fine. Tried resetting the token, in case something got messed up there, which seems unlikely, but did it either way. API requests are working fine on my own and in the explorer, but not in the Homey app…
Just shooting for the stars here, but since the Bridge is in the cloud, and the app probably sends request to the Tibber API from the same IP address for a lot of people, maybe the API recognized the IP as spam, and blocked it/timed it out? Or even banned it automatically?

**Comment by jstaro** [comment] 2022-01-03 15:26
Thanks for testing!

We are currently investigating our infrastructure to see where these connection errors occur (we cannot currently see these errors on our end). Diagnostic logging of this should be improved in the upcoming version (including showing the HTTP status code in that particular view).

Rate-limiting could definitely occur, but it should only be intermittent. We have reached out to Athom for some details so we can ensure we do not aggressively rate-limit their datacenter location.

**Comment by jstaro** [comment] 2022-01-03 21:14
@Coderaxx We have made some changes so please try again now.

**Comment by lovethyresson** [comment] 2022-01-11 09:53
Should be fixed in 1.5.14, please reopen if not fixed.

**Closed by lovethyresson** 2022-01-11 09:53 UTC
